# Generated by Django 5.2.17 on 2026-09-12 20:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_clear_unneeded_answers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=64, unique=True)),
                ('subject_id_at_request', models.PositiveIntegerField()),
                ('subject_joined_at', models.DateTimeField()),
                ('received_on', models.DateField()),
                ('verification_method', models.CharField(max_length=20)),
                ('verified_on', models.DateField()),
                ('action', models.CharField(max_length=16)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.JSONField(default=dict)),
                ('replied_on', models.DateField(blank=True, null=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='privacy_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'operazione privacy',
                'verbose_name_plural': 'operazioni privacy',
            },
        ),
    ]
